### ISSUE TITLE
'no actor found for key' after a lot of calls to tcp-published actor

### ISSUE THREAD

**Issue by julianrz** [RuedigerMoeller/kontraktor#17]
This code works for a few minutes and then looks like actor is no longer there, repeatedly prints:
E 20:58:56:791 : tcp receiver :  : registry:836420849 no actor found for key RemoteCallEntry{receiverKey=1, futureKey=-2138972716, method='greet', args=[[B@54472710], queue=0}

org.nustaq.kontraktor.KTimeoutException: Timeout
    at org.nustaq.kontraktor.Promise.awaitHelper(Promise.java:450)
    at org.nustaq.kontraktor.Promise.await(Promise.java:392)
    at org.nustaq.kontraktor.IPromise.await(IPromise.java:147)
    at com.company.Main$6.lambda$run$1(Main.java:157)
    at com.company.Main$6$$Lambda$23/1821835811.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at com.company.Main$6.run(Main.java:156)

Does not look like it is out of memory when it fails. Tried several versions, including latest. 

It is run with the following options -Xmx16g -XX:+UseG1GC; machine has 12 virtual cores and 64Gb total RAM
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

```
package com.company;

import org.nustaq.kontraktor.Actor;
import org.nustaq.kontraktor.IPromise;
import org.nustaq.kontraktor.Promise;

public class HelloActor extends Actor<HelloActor> {
    public IPromise<Integer> greet( byte[] b ) {
        return new Promise<>(b.length);
    }
}
package com.company;

import org.nustaq.kontraktor.Callback;
import org.nustaq.kontraktor.IPromise;
import org.nustaq.kontraktor.remoting.base.ActorClientConnector;
import org.nustaq.kontraktor.remoting.base.ConnectableActor;
import org.nustaq.kontraktor.remoting.encoding.SerializerType;
import org.nustaq.kontraktor.remoting.tcp.TCPPublisher;

import java.util.ArrayList;
import java.util.List;

import static org.nustaq.kontraktor.Actors.AsActor;

public class Main {

    public static void main(String[] args) throws InterruptedException {
        testRemote();
    }

   static void testRemote() throws InterruptedException {
        HelloActor myService  = AsActor(HelloActor.class,10000000);

        Thread tpub = new Thread() {
            public void run() {
                try {
                    new TCPPublisher()
                            .facade(myService)
                            .port(8181)
                            .serType(SerializerType.FSTSer)
                            .publish();
                } catch(Exception ex){
                    ex.printStackTrace();
                }
            }
        };
        tpub.start();

        ConnectableActor con = new org.nustaq.kontraktor.remoting.tcp.TCPConnectable(HelloActor.class, "localhost", 8181);

        Callback<ActorClientConnector> disconnectCallback = new Callback<ActorClientConnector>() {
            @Override
            public void complete(ActorClientConnector actorClientConnector, Object o) {
                System.out.println("disconnect");
            }
        };

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        HelloActor act = (HelloActor) con.connect(disconnectCallback).await();

        Thread thmain = new Thread() {
            public void run() {
                callActor(act);
            }
        };

        thmain.setName("caller");
        thmain.start();

        Thread thmain2 = new Thread() {
            public void run() {
               callActor(act);
            }
        };
        thmain2.setName("caller2");
        thmain2.start();

        thmain.join();
        thmain2.join();
        System.out.println("main threads finished");
    }

    static void callActor(HelloActor act) {
        byte [] bb = new byte[500];
        long n=1000000;
        try {
            while (true) {

                List<IPromise<Integer>> l = new ArrayList<>();
                for (long i = 0; i < n; i++) {
                    l.add(act.greet(bb));
                }

                l.forEach((integerIPromise) -> {
                    try{integerIPromise.await();}catch(Throwable th){th.printStackTrace();}
                });

                l.forEach(p -> {
                    try {
                        p.get();
                    } catch (Throwable th) {
                        th.printStackTrace();
                    }
                });
            }
        } catch(Throwable th){
            th.printStackTrace();
        }
    }
}
```

**Comment by RuedigerMoeller** [comment]
Thanks for reporting, I'll try to reproduce this

**Comment by RuedigerMoeller** [comment]
1) Note that kontraktor uses bounded queues, so your test fills up the queue and then blocks the executing thread.
2) the default implementation of await is `await(15000)`. So if the promise is not resolved within 15 seconds, a timeout exception is thrown, which in turn will abort the connection (default behaviour on uncatched, might be worth a rethink :) ).

This is a classical synthetic benchmark issue as you create synthetic overload filling all queues as fast as possible, queuing in turn then leads to latency and in your case timeout (I don't have this on my test machine, but its likely this might happen). Note that await() already returns the result, so the second loop calling "get" is superflous.

A real event/reactive system would not even allow 1 million unanswered request (need a fuse mechanism to avoid such overload). Actor systems dislike overload as large queues slow down even more.

see 
https://github.com/RuedigerMoeller/kontraktor/blob/trunk/src/test/java/kontraktor/Issue17.java

on how to apply backpressure in case of bulk request response as in your sample.

Note I added some variants on your code to illustrate alternative uses of the API.

**Comment by RuedigerMoeller** [comment]
[edit: i was wrong + offtopic ;) ]

**Comment by RuedigerMoeller** [comment]
..

**Comment by julianrz** [comment]
No, I am not running inside a VM, this is a JVM:)
I disagree, in real life a queue of any size can fill up within seconds due to a large spike in traffic, and 1 million messages backlog is absolutely nothing (I have to design for 100k/sec sustained rate) - better behave well in this case...
The issue is not that I got a timeout - with this kind of overload it is expected. The issue is that the actor stopped being responsive altogether, giving this line: "E 20:58:56:791 : tcp receiver : : registry:836420849 no actor found for key", after a fairly long and happy session
If it works for you, leave it running overnight.

**Comment by RuedigerMoeller** [comment]
[edit] removed completely wrong analysis ..

I missed that you already modified the queue size of the HelloActor. However on remote side still the default queue size will be used, so you might want to test with:

``` java
            ConnectableActor con = 
                new TCPConnectable(HelloActor.class, "localhost", 8181)
                    .inboundQueueSize(10_000_000); // <= change
```

else the sending side will operate with a 32k queue while the remote hello actor has a queue size of 10 million.

**Comment by RuedigerMoeller** [comment]
[edit: wrong analysis]

**Comment by RuedigerMoeller** [comment]
I could reproduce it (after quite some time). Seems like an int/sequence overflow .. many thanks for reporting and insisting, will provide a fix as soon as possible

**Comment by julianrz** [comment]
OSX 10.8.5

**Comment by RuedigerMoeller** [comment]
It turns out the callbackId (integer) gets an overflow in your use case. Depending on load and uptime of a system this can be a very real issue in a productive system. At 200k messages/sec with a Promise result, it takes roughly 180 minutes until this happens.

I moved the callbackId type to long which should be sufficient even for 24x7 systems.

Fixed and validated with 3.11 (available on maven.org ~1-3 days)

**Comment by julianrz** [comment]
Thanks for quick action, but you have fixed something else (good!). My issue is still there in 3.11. 

I put a breakpoint on Log.msg call, right before it happens, there is severity 0 message: "a connection closed '-2147483648', terminating registry". Logged from RemoteRegistry.writeObject() exception handler block. The exception it got is: ArrayIndexOutOfBoundsException: -2147483648.

**Comment by RuedigerMoeller** [comment]
hm .. so its a regular connection close (as initially assumed). This also indicates why it took me hours to reproduce :).
If the connection closes, terminating the associated registry (mapping remote/callback mappings and stuff) is correct behaviour. However in your case it seems the connection is _not_ closed as you still receive messages.
I had some issues with windows network stack (i am developing Linux on mostly), as the windoze network stack behaves differently on disconnect. There might be similar issues with os x
- I'll try running the test overnight again.
- could you please check if the issue also occurs if you replace `TCPPublisher` by `TCPNIOPublisher` (client connector can stay same). Though the NIO stuff is less tested it might show different behaviour and could indicate where the problem is. Thanks in advance :D

**Comment by julianrz** [comment]
Sure! But did the registry close because of ArrayIndexOutOfBoundsException - or was there an ArrayIndexOutOfBoundsException because the registry closed:) BTW is it still the integer overflow, otherwise why negative index? Also what happens if Long overflows(still possible, but will take a long time)? I think it should wrap around and start with 0 then...
-Julian

```
 On Saturday, October 17, 2015 10:06 AM, moru0011 <notifications@github.com> wrote:
```

 hm .. so its a regular connection close (as initially assumed). This also indicates why it took me hours to reproduce :).
If the connection closes, terminating the associated registry (mapping remote/callback mappings and stuff) is correct behaviour. However in your case it seems the connection is not closed as you still receive further messages.
I had some issues with windows network stack (i am developing on mostly), as the windoze network stack behaves differently on disconnect.   
- I'll try running the test overnight again.
- could you please check if the issue also occurs if you replace TCPPublisher by TCPNIOPublisher (client connector can stay same). Though the NIO stuff is less tested it might show different behaviour and could indicate where the problem is. Thanks in advance :D

**Comment by RuedigerMoeller** [comment]
yeah the negative futureId is suspicious (and probably the reason for AIBE). 

Maybe i messed up (either build or test or both) :), i will recheck. Regarding Long: it won't overflow even at high rates (just do the math). Note the callback id is not global but on a sender-receiver base.
In fact a single (int) cast somewhere negates the int=>long change. I will recheck this once I find time.  I still assume its kind of overflow as kontraktor runs in a production system 10 hours with peaks of >100k events/second. However those peaks do only hold for some seconds, average is more like 2-5k. So most probably (and hopefully) not a magical concurrency issue ..

**Comment by RuedigerMoeller** [comment]
have you tried with NIOTCPPublisher ?

**Comment by RuedigerMoeller** [comment]
could reproduce again .. my bad, did not retest long enough .. will need some time to nail that ..

**Comment by RuedigerMoeller** [comment]
Update/**Workaround**: I could not reproduce this with TCPNIOPublisher. Until a fix is available, don't use TCPPublisher (as of 3.11). TCPNIOPublisher scales much better than TCPPublisher at cost of ~5-10% peak throughput.

**Comment by RuedigerMoeller** [comment]
version 3.16 defaulting to unbounded queues apparently fixes this. Still the testcase contains some performance killers:
- sending a batch of 1 million actually triggers build up of a callback map of ~1million unresponded "open" requests (`IPromise request()` actually is a request response pattern). This is costly. Limiting the number of unreplied requests to 200k increases throughput significantly
- using `await()` on each individual promise is very costly. Prefer `all(promise).await()`. stack based `await()` as implemented in kontraktor is convenient to make common stuff like intialization etc look `pseudo-synchronous`. Do not use await for high throughput code. 
- Always prefer TCPNIOPublisher over TCPPublisher (Deprecated with 3.16) 

``` java
        static void callActor(HelloActor act) {
            byte [] bb = new byte[500];
            long n=1_000_000; // reduction to 200k increases throughput significantly (less queuing and callback management)
            try {
                while (true) {
                    long tim = System.currentTimeMillis();
                    List<IPromise<Integer>> l = new ArrayList<>();
                    for (long i = 0; i < n; i++) {
                        l.add(act.greet(bb));
                    }

// slow:
//                    l.forEach((integerIPromise) -> {
//                        try{integerIPromise.await();}catch(Throwable th){th.printStackTrace();}
//                    });
                    all(l).await(30_000); // better, even better would be elimination of await() using 'then()'

                    l.forEach(p -> {
                        try {
                            p.get();
                        } catch (Throwable th) {
                            th.printStackTrace();
                        }
                    });
                    System.out.println(""+(System.currentTimeMillis()-tim));
                }
            } catch(Throwable th){
                th.printStackTrace();
            }
        }
```
